# Local variables for common configurations
locals {
  common_tags = {
    Environment = var.environment
    ManagedBy   = "Terraform"
    Workspace   = "nx-mcp"
  }

  # Build output paths
  dist_path = "${path.module}/../../dist"

  # Worker name prefix for environment separation
  worker_prefix = var.environment == "production" ? "" : "${var.environment}-"
}

# MCP Server deployments are dynamically generated
# See affected-apps.tf (auto-generated by scripts/generate-affected-config.js) 